### ISSUE TITLE
Stuck in step2,just report error when enabling services

### ISSUE THREAD

**Issue by OptimusPrimeme** [xyou365/AutoRclone#42]
```shell
python gen_sa_accounts.py --quick-setup 1 --new-only                                             
creat projects: 1
Creating 1 projects
Enabling services
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 323, in <module>
    download_keys=args.download_keys
  File "gen_sa_accounts.py", line 224, in serviceaccountfactory
    _enable_services(serviceusage,ste,services)
  File "gen_sa_accounts.py", line 89, in _enable_services
    batch.execute()
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\googleapiclient\http.py", line 1524, in execute
    self._execute(http, self._order, self._requests)
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\googleapiclient\http.py", line 1454, in _execute
    self._batch_uri, method="POST", body=body, headers=headers
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\httplib2\__init__.py", line 1994, in request
    cachekey,
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\httplib2\__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\httplib2\__init__.py", line 1557, in _conn_request
    conn.connect()
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\httplib2\__init__.py", line 1391, in connect
    raise socket_err
  File "G:\software\code\Anaconda\envs\test\lib\site-packages\httplib2\__init__.py", line 1326, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "G:\software\code\Anaconda\envs\test\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "G:\software\code\Anaconda\envs\test\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "G:\software\code\Anaconda\envs\test\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by OptimusPrimeme** [comment]
Maybe I found the reason that there are some questions when running clash in rule mode.I just turnt to global mode.

**Comment by tanpengsccd** [comment]
> Maybe I found the reason that there are some questions when running clash in rule mode.I just turnt to global mode.

You save my time.
