### ISSUE TITLE
run gen_sa_accounts.py failed；PermissionError: [Errno 13] Permission denied: 'token.pickle'

### ISSUE THREAD

**Issue by wateroader** [xyou365/AutoRclone#57]
$ python3 gen_sa_accounts.py --quick-setup 1 
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=95576504074-3o3c4a8au0m9fplnc88blv37psg35ghu.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam&state=PjP63ZjIxkrLDfbyRPtsyOmKh0HHGE&prompt=consent&access_type=offline
Enter the authorization code: *********************************
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "gen_sa_accounts.py", line 175, in serviceaccountfactory
    with open(token, 'wb') as t:
PermissionError: [Errno 13] Permission denied: 'token.pickle'
![2020-08-12 19-05-56 的屏幕截图](https://user-images.githubusercontent.com/52651121/90017643-6a26ce80-dcde-11ea-92a4-4a5ba7c99819.png)

**Comment by theg00s3** [comment]
what are the permissions of the token.pickle file?

**Comment by shivangswain** [comment]
Have you been able to resolve this issue because I am facing the same problem?

**Comment by shivangswain** [comment]
This can be fixed by just moving the AutoRclone folder to another user accessible and modifiable directory like the Desktop. Had this issue and moving the folder resolved the issue.
