### ISSUE TITLE
AttributeError: 'Http' object has no attribute 'close'

### ISSUE THREAD

**Issue by Enf0** [xyou365/AutoRclone#61]
When trying to generate service accounts, I get the following error:

```
# python3 gen_sa_accounts.py --quick-setup 1
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "gen_sa_accounts.py", line 178, in serviceaccountfactory
    cloud = build('cloudresourcemanager', 'v1', credentials=creds)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery.py", line 300, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'
```

Any idea why? Thanks.

**Comment by gyutw** [comment]
Same for me:
```
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "gen_sa_accounts.py", line 178, in serviceaccountfactory
    cloud = build('cloudresourcemanager', 'v1', credentials=creds)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery.py", line 300, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'
```

**Comment by Enf0** [comment]
Seems to be a bug in the lastest version (1.12.2) of [googleapis/google-api-python-client](https://github.com/googleapis/google-api-python-client) according to [this](https://github.com/googleapis/google-api-python-client/issues/1047) and [this](https://github.com/googleapis/google-api-python-client/issues/1046) issue.

I solved it by manually installing 1.12.1 instead:
`pip3 install google-api-python-client==1.12.1`

**Comment by yohplala** [comment]
Guys, did you update your `httplib2` to the last version as well?
I have not tested on my side the last google api python client, but I am aware the last version makes use of `close()` method of `http` object from `httplib2`.
I don't know when this method was added, but maybe it was not existing with the version of `httplib2` you are using.
Bests

**Comment by calvin-dani** [comment]
AttributeError: 'Resource' object has no attribute 'close'.

The problem does persist

**Comment by Vesanius** [comment]
how do i update httplib2? i can't uninstall it, and if i install it with `pip install httplib 2` it says that it is already installed.

**Comment by yongxin1024** [comment]
> AttributeError: 'Resource' object has no attribute 'close'.
> 
> The problem does persist

yes, me too
