### ISSUE TITLE
python3 gen_sa_accounts.py --quick-setup 1 --new-only

### ISSUE THREAD

**Issue by xhrzg2017** [xyou365/AutoRclone#94]
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "gen_sa_accounts.py", line 178, in serviceaccountfactory
    cloud = build('cloudresourcemanager', 'v1', credentials=creds)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/discovery.py", line 321, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'

**Comment by xhrzg2017** [comment]
.
