### ISSUE TITLE
AttributeError: 'Http' object has no attribute 'close'

### ISSUE THREAD

**Issue by whistle003** [xyou365/AutoRclone#97]
root@instance-1:~/AutoRclone# python3 gen_sa_accounts.py --list-projects
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 323, in <module>
    download_keys=args.download_keys
  File "gen_sa_accounts.py", line 178, in serviceaccountfactory
    cloud = build('cloudresourcemanager', 'v1', credentials=creds)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery.py", line 321, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'

**Comment by asljkdhu1inadsuhdipsaud** [comment]
resolved?

**Comment by asljkdhu1inadsuhdipsaud** [comment]
Solved?

**Comment by whistle003** [comment]
> Solved?

`pip3 install 'google-api-python-client>=1.12.1'`
